apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql-pv-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
      containers:
      - image: mysql:5.7
        name: mysql
        envFrom:
        - secretRef:
            name: mysql-secret
        - configMapRef:
            name: mysql-cm
        # env:
        # - name: MYSQL_ROOT_PASSWORD
        #   value: P123456
        # - name: MYSQL_DATABASE
        #   value: phonebook
        # - name: MYSQL_USER
        #   value: clarus
        # - name: MYSQL_PASSWORD
        #   value: Clarusway_1
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: mysql-pv-storage
        ports:
        - containerPort: 3306